function write_psap_csv_for_ML(psap1s)

fout_name = strrep(psap1s.fname,'.nc','_.csv');

vdata = psap1s.vdata;
vdata.time = psap1s.time;
fid = fopen(fout_name,'w');
fprintf(fid,[repmat('%s ,',1,13), '%s \n'],'yyyy-mm-dd HH:MM:SS',...
   'Ba_B','Ba_B_good==1','Ba_G','Ba_G_good==1','Ba_R','Ba_R_good==1',...
   'Impactor_state','sample_flow_rate','sample_volume',...
   'transmittance_blue','transmittance_green','transmittance_red','filter_unstable');
for i = 1:length(vdata.time)
   row = {datestr(vdata.time(i),'yyyy-mm-dd HH:MM:SS'), ...
      vdata.Ba_B(i), vdata.qc_Ba_B(i)==0, ...
      vdata.Ba_G(i), vdata.qc_Ba_G(i)==0, ...
      vdata.Ba_R(i), vdata.qc_Ba_R(i)==0, ...
      vdata.impactor_state(i),vdata.sample_flow_rate(i), vdata.sample_volume(i), ...
      vdata.transmittance_blue(i), vdata.transmittance_green(i), vdata.transmittance_red(i),...
      vdata.filter_unstable(i)};
   fprintf(fid,'%s , %2.4e , %1d , %2.4e , %1d , %2.4e , %1d  , %1d , %2.4e , %2.4e, %2.4e, %2.4e, %2.4e, %1d \n',row{:});
   if mod(i,10000)==0
      disp(i)
   end
end
fclose(fid);

return
