%This was mostly bust, comparing a bunch of Io collections that much good

ARM_Langley_Ios = ancload(['F:\case_studies\fkb\fkbmfrsrlangleyM1.c1\fkbmfrsrlangleyM1.c1.20070321.153000.cdf']);

sm_Ios = loadinto(['F:\case_studies\fkb\Ios.mat']); %Presumably smoothed Ios pulled from ARM aod files.
md = 'F:\case_studies\fkb\fkbmfrsrM1.b1\lang_Io_mats\';
my_langs_1 = loadinto([md,'lang_Ios_raw.v1.mat']);
my_langs_2 = loadinto([md,'lang_Ios_raw.v2.mat']);
my_langs_3 = loadinto([md,'lang_Ios_raw.v3.mat']);
my_langs_5 = loadinto([md,'lang_Ios_raw.v5.mat']);
my_langs_6 = loadinto([md,'lang_Ios_raw.v6.mat']);
my_langs_7 = loadinto([md,'lang_Ios_raw.v7.mat']);

%%
filt = 1;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(serial2doy(ARM_Langley_Ios.time(ARM>0)), ARM(ARM>0), 'k.',...
   serial2doy(ARM_Langley_Ios.time(good)), ARM(good), 'ro',...
      serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data, '-ms', ...
   serial2doy(my_langs_6.time),my_langs_6.(['Vo_filter',num2str(filt)]) , 'b.',...
   serial2doy(my_langs_7.time),my_langs_7.(['Vo_filter',num2str(filt)]) , 'g.',...
   serial2doy(my_langs_3.time),my_langs_3.(['Vo_filter',num2str(filt)]) , 'r.',...
   serial2doy(my_langs_6.IQF.time), my_langs_6.IQF.(['filter',num2str(filt)]),'bo',...   
serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)]),'go',...
   serial2doy(my_langs_3.IQF.time), my_langs_3.IQF.(['filter',num2str(filt)]),'ko')
legend('all ARM','good ARM','ARM IQF','my 6','my 7','my 3', 'IQF6','IQF7','IQF3')
title(['Io filter ',num2str(filt)])
%%
filt = 2;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(serial2doy(ARM_Langley_Ios.time(ARM>0)), ARM(ARM>0), 'k.',...
   serial2doy(ARM_Langley_Ios.time(good)), ARM(good), 'ro',...
      serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data, '-ms', ...
   serial2doy(my_langs_6.time),my_langs_6.(['Vo_filter',num2str(filt)]) , 'b.',...
   serial2doy(my_langs_7.time),my_langs_7.(['Vo_filter',num2str(filt)]) , 'g.',...
   serial2doy(my_langs_3.time),my_langs_3.(['Vo_filter',num2str(filt)]) , 'r.',...
   serial2doy(my_langs_6.IQF.time), my_langs_6.IQF.(['filter',num2str(filt)]),'bo',...   
serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)]),'go',...
   serial2doy(my_langs_3.IQF.time), my_langs_3.IQF.(['filter',num2str(filt)]),'ko')
legend('all ARM','good ARM','ARM IQF','my 6','my 7','my 3', 'IQF6','IQF7','IQF3')
title(['Io filter ',num2str(filt)])
%%
filt = 3;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(serial2doy(ARM_Langley_Ios.time(ARM>0)), ARM(ARM>0), 'k.',...
   serial2doy(ARM_Langley_Ios.time(good)), ARM(good), 'ro',...
      serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data, '-ms', ...
   serial2doy(my_langs_6.time),my_langs_6.(['Vo_filter',num2str(filt)]) , 'b.',...
   serial2doy(my_langs_7.time),my_langs_7.(['Vo_filter',num2str(filt)]) , 'g.',...
   serial2doy(my_langs_3.time),my_langs_3.(['Vo_filter',num2str(filt)]) , 'r.',...
   serial2doy(my_langs_6.IQF.time), my_langs_6.IQF.(['filter',num2str(filt)]),'bo',...   
serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)]),'go',...
   serial2doy(my_langs_3.IQF.time), my_langs_3.IQF.(['filter',num2str(filt)]),'ko')
legend('all ARM','good ARM','ARM IQF','my 6','my 7','my 3', 'IQF6','IQF7','IQF3')
title(['Io filter ',num2str(filt)])
%%
filt = 4;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(serial2doy(ARM_Langley_Ios.time(ARM>0)), ARM(ARM>0), 'k.',...
   serial2doy(ARM_Langley_Ios.time(good)), ARM(good), 'ro',...
      serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data, '-ms', ...
   serial2doy(my_langs_6.time),my_langs_6.(['Vo_filter',num2str(filt)]) , 'b.',...
   serial2doy(my_langs_7.time),my_langs_7.(['Vo_filter',num2str(filt)]) , 'g.',...
   serial2doy(my_langs_3.time),my_langs_3.(['Vo_filter',num2str(filt)]) , 'r.',...
   serial2doy(my_langs_6.IQF.time), my_langs_6.IQF.(['filter',num2str(filt)]),'bo',...   
serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)]),'go',...
   serial2doy(my_langs_3.IQF.time), my_langs_3.IQF.(['filter',num2str(filt)]),'ko')
legend('all ARM','good ARM','ARM IQF','my 6','my 7','my 3', 'IQF6','IQF7','IQF3')
title(['Io filter ',num2str(filt)])
%%
filt = 5;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(serial2doy(ARM_Langley_Ios.time(ARM>0)), ARM(ARM>0), 'k.',...
   serial2doy(ARM_Langley_Ios.time(good)), ARM(good), 'ro',...
      serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data, '-ms', ...
   serial2doy(my_langs_6.time),my_langs_6.(['Vo_filter',num2str(filt)]) , 'b.',...
   serial2doy(my_langs_7.time),my_langs_7.(['Vo_filter',num2str(filt)]) , 'g.',...
   serial2doy(my_langs_3.time),my_langs_3.(['Vo_filter',num2str(filt)]) , 'r.',...
   serial2doy(my_langs_6.IQF.time), my_langs_6.IQF.(['filter',num2str(filt)]),'bo',...   
serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)]),'go',...
   serial2doy(my_langs_3.IQF.time), my_langs_3.IQF.(['filter',num2str(filt)]),'ko')
legend('all ARM','good ARM','ARM IQF','my 6','my 7','my 3', 'IQF6','IQF7','IQF3')
title(['Io filter ',num2str(filt)])
%%

%%
filt = 1;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(...
   serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data./mean(sm_Ios.vars.(['Io_filter',num2str(filt)]).data), '-ms', ...
   serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)])./mean(my_langs_7.IQF.(['filter',num2str(filt)])),'go',...
   serial2doy(lang_common_c0.IQF.time), lang_common_c0.IQF.(['filter',num2str(filt)])./mean(lang_common_c0.IQF.(['filter',num2str(filt)])),'ko')
legend('ARM IQF','IQF7','IQF_c0')
title(['Io filter ',num2str(filt)])

%%
filt = 2;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(...
   serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data./mean(sm_Ios.vars.(['Io_filter',num2str(filt)]).data), '-ms', ...
   serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)])./mean(my_langs_7.IQF.(['filter',num2str(filt)])),'go',...
   serial2doy(lang_common_c0.IQF.time), lang_common_c0.IQF.(['filter',num2str(filt)])./mean(lang_common_c0.IQF.(['filter',num2str(filt)])),'ko')
legend('ARM IQF','IQF7','IQF_c0')
title(['Io filter ',num2str(filt)])

%%
filt = 3;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(...
   serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data./mean(sm_Ios.vars.(['Io_filter',num2str(filt)]).data), '-ms', ...
   serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)])./mean(my_langs_7.IQF.(['filter',num2str(filt)])),'go',...
   serial2doy(lang_common_c0.IQF.time), lang_common_c0.IQF.(['filter',num2str(filt)])./mean(lang_common_c0.IQF.(['filter',num2str(filt)])),'ko')
legend('ARM IQF','IQF7','IQF_c0')
title(['Io filter ',num2str(filt)])

%%
filt = 4;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(...
   serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data./mean(sm_Ios.vars.(['Io_filter',num2str(filt)]).data), '-ms', ...
   serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)])./mean(my_langs_7.IQF.(['filter',num2str(filt)])),'go',...
   serial2doy(lang_common_c0.IQF.time), lang_common_c0.IQF.(['filter',num2str(filt)])./mean(lang_common_c0.IQF.(['filter',num2str(filt)])),'ko')
legend('ARM IQF','IQF7','IQF_c0')
title(['Io filter ',num2str(filt)])

%%
filt = 5;
ARM = ARM_Langley_Ios.vars.(['michalsky_solar_constant_sdist_filter',num2str(filt)]).data;
good = ARM_Langley_Ios.vars.(['michalsky_badflag_filter',num2str(filt)]).data==0;
figure; plot(...
   serial2doy(sm_Ios.time), sm_Ios.vars.(['Io_filter',num2str(filt)]).data./mean(sm_Ios.vars.(['Io_filter',num2str(filt)]).data), '-ms', ...
   serial2doy(my_langs_7.IQF.time), my_langs_7.IQF.(['filter',num2str(filt)])./mean(my_langs_7.IQF.(['filter',num2str(filt)])),'go',...
   serial2doy(lang_common_c0.IQF.time), lang_common_c0.IQF.(['filter',num2str(filt)])./mean(lang_common_c0.IQF.(['filter',num2str(filt)])),'ko')
legend('ARM IQF','IQF7','IQF_c0')
title(['Io filter ',num2str(filt)])

%%
