function figure1 = createdailyAOTplot(X1, YMatrix1, label)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-Jun-2014 12:31:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create title
title(label);

% Create multiple lines using matrix input to plot
plot(X1, YMatrix1,'.'); 
legend('415 nm','500 nm','615 nm', '673 nm','870 nm','940 nm')
% plot1 = plot(X1,YMatrix1,'Parent',axes1);
% set(plot1(1),'DisplayName','415');
% set(plot1(2),'DisplayName','500');
% set(plot1(3),'DisplayName','600');
% set(plot1(4),'DisplayName','700');
% set(plot1(5),'DisplayName','900');
% set(plot1(6),'DisplayName','940');

% Create ylabel
ylabel({'AOD'});

% Create legend
% legend(axes1,'show');

