%%
mfr_aod = plot_qcs(ancload(getfullname_('*.cdf','mfr_aodaod')));
%%
% The function "qc_impacts" rolls up the individual QC tests to yield
% values of 0, 1, 2 for 'good', 'indeterminate', and 'bad'.
good = qc_impacts(mfr_aod.vars.qc_aerosol_optical_depth_filter1)<2;
good = good&qc_impacts(mfr_aod.vars.qc_aerosol_optical_depth_filter2)<2;
good = good&qc_impacts(mfr_aod.vars.qc_aerosol_optical_depth_filter3)<2;
good = good&qc_impacts(mfr_aod.vars.qc_aerosol_optical_depth_filter4)<2;
good = good&qc_impacts(mfr_aod.vars.qc_aerosol_optical_depth_filter5)<2;
good = good&qc_impacts(mfr_aod.vars.qc_angstrom_exponent)<2;


figure; 
s(1) = subplot(2,1,1);
plot(serial2Hh(mfr_aod.time(good)), mfr_aod.vars.aerosol_optical_depth_filter1.data(good),'b.',...
serial2Hh(mfr_aod.time(good)), mfr_aod.vars.aerosol_optical_depth_filter2.data(good),'g.',...
serial2Hh(mfr_aod.time(good)), mfr_aod.vars.aerosol_optical_depth_filter3.data(good),'c.',...
serial2Hh(mfr_aod.time(good)), mfr_aod.vars.aerosol_optical_depth_filter4.data(good),'m.',...
serial2Hh(mfr_aod.time(good)), mfr_aod.vars.aerosol_optical_depth_filter5.data(good),'r.',...
serial2Hh(mfr_aod.time(~good)), mfr_aod.vars.aerosol_optical_depth_filter1.data(~good),'k.',...
serial2Hh(mfr_aod.time(~good)), mfr_aod.vars.aerosol_optical_depth_filter2.data(~good),'k.',...
serial2Hh(mfr_aod.time(~good)), mfr_aod.vars.aerosol_optical_depth_filter3.data(~good),'k.',...
serial2Hh(mfr_aod.time(~good)), mfr_aod.vars.aerosol_optical_depth_filter4.data(~good),'k.',...
serial2Hh(mfr_aod.time(~good)), mfr_aod.vars.aerosol_optical_depth_filter5.data(~good),'k.');
legend('415 nm','500 nm','615 nm', '673 nm', '870 nm','rejected')
s(2) = subplot(2,1,2);
plot(serial2Hh(mfr_aod.time(good)), mfr_aod.vars.angstrom_exponent.data(good), 'go',...
   serial2Hh(mfr_aod.time(~good)), mfr_aod.vars.angstrom_exponent.data(~good), 'kx' );
legend('Angstrom Exponent', 'rejected');
linkaxes(s,'x');
