%%
lang = ancload;
%
goodm_all = find(lang.vars.michalsky_badflag_filter1.data==0&...
   lang.vars.michalsky_badflag_filter2.data==0&...
   lang.vars.michalsky_badflag_filter3.data==0&...
   lang.vars.michalsky_badflag_filter4.data==0&...
   lang.vars.michalsky_badflag_filter5.data==0);
goodb_all = find(lang.vars.barnard_badflag_filter1.data==0 & ...
   lang.vars.barnard_badflag_filter2.data==0 & ...
   lang.vars.barnard_badflag_filter3.data==0 & ...
   lang.vars.barnard_badflag_filter4.data==0 & ...
   lang.vars.barnard_badflag_filter5.data==0 & ...
   lang.vars.barnard_solar_constant_sdist_filter1.data > 0 & ...
lang.vars.barnard_solar_constant_sdist_filter2.data > 0 & ...
   lang.vars.barnard_solar_constant_sdist_filter3.data > 0 & ...
   lang.vars.barnard_solar_constant_sdist_filter4.data > 0 & ...
   lang.vars.barnard_solar_constant_sdist_filter5.data > 0 );
good_all = intersect(goodm_all, goodb_all);

[lang_good] = ancsift(lang, lang.dims.time, good_all);
figure; plot(lang_good.time, lang_good.vars.michalsky_solar_constant_sdist_filter2.data, 'g.',lang_good.time, lang_good.vars.barnard_solar_constant_sdist_filter2.data, 'b.'); datetick('keeplimits')
legend('Michalsky','Barnard');
[pname, fname]= fileparts(lang.fname);
title(['Screened Io values for filter 2 from ',fname],'interpreter','none');
%%
V = datevec(lang.time(good_all));
[pname,fname] = fileparts(lang.fname);
yyyy = V(:,1);
mm = V(:,2);
dd = V(:,3);
HH = V(:,4);
MM = V(:,5);
SS = V(:,6);
doy0 = serial2doy0(lang.time(good_all))';
HHhh = (doy0 - floor(doy0)) *24;
%%
txt_out = [yyyy, mm, dd, HH, MM, SS, doy0, HHhh, ...
    lang.vars.barnard_solar_constant_sdist_filter1.data(good_all)',...
    lang.vars.barnard_solar_constant_sdist_filter2.data(good_all)',...
    lang.vars.barnard_solar_constant_sdist_filter3.data(good_all)',...
    lang.vars.barnard_solar_constant_sdist_filter4.data(good_all)',...
    lang.vars.barnard_solar_constant_sdist_filter5.data(good_all)',...
    lang.vars.barnard_solar_constant_sdist_filter6.data(good_all)',...
    lang.vars.michalsky_solar_constant_sdist_filter1.data(good_all)',...
    lang.vars.michalsky_solar_constant_sdist_filter2.data(good_all)',...
    lang.vars.michalsky_solar_constant_sdist_filter3.data(good_all)',...
    lang.vars.michalsky_solar_constant_sdist_filter4.data(good_all)',...
    lang.vars.michalsky_solar_constant_sdist_filter5.data(good_all)',...
    lang.vars.michalsky_solar_constant_sdist_filter6.data(good_all)'];
%%
header_row = ['yyyy, mm, dd, HH, MM, SS, doy0, HHhh, '];
header_row = [header_row, 'Io_415nm_barnard, Io_500nm_barnard, '];
header_row = [header_row, 'Io_615nm_barnard, Io_673nm_barnard, '];
header_row = [header_row, 'Io_870nm_barnard, Io_940nm_barnard, '];
header_row = [header_row, 'Io_415nm_mich, Io_500nm_mich, '];
header_row = [header_row, 'Io_615nm_mich, Io_673nm_mich, '];
header_row = [header_row, 'Io_870nm_mich, Io_940nm_mich'];
format_str = ['%d, %d, %d, %d, %d, %d, %3.6f, %2.4f, '];
format_str = [format_str, '%2.3f, %2.3f, '];
format_str = [format_str, '%2.3f, %2.3f, '];
format_str = [format_str, '%2.3f, %2.3f, '];
format_str = [format_str, '%2.3f, %2.3f, '];
format_str = [format_str, '%2.3f, %2.3f, '];
format_str = [format_str, '%2.3f, %2.3f \n '];
%%

fid = fopen([pname, '/', fname, '.txt'],'wt');
fprintf(fid,'%s \n',header_row );
fprintf(fid,format_str,txt_out');
fclose(fid);
%%

