nsa = plot_qcs;
%%

figure(1); 
s(1) = subplot(3,1,1);plot(serial2doy(nsa.time), [nsa.vars.direct_normal_narrowband_filter1.data; ...
    nsa.vars.direct_normal_narrowband_filter2.data; nsa.vars.direct_normal_narrowband_filter3.data; ...
    nsa.vars.direct_normal_narrowband_filter4.data; nsa.vars.direct_normal_narrowband_filter5.data],'-');
ylabel('dirn');
s(2) = subplot(3,1,2);
plot(serial2doy(nsa.time), [nsa.vars.aerosol_optical_depth_filter1.data; ...
    nsa.vars.aerosol_optical_depth_filter2.data; nsa.vars.aerosol_optical_depth_filter3.data; ...
    nsa.vars.aerosol_optical_depth_filter4.data; nsa.vars.aerosol_optical_depth_filter5.data],'-');
ylabel('aod');
s(3) = subplot(3,1,3);
plot(serial2doy(nsa.time), [nsa.vars.direct_normal_transmittance_filter1.data; ...
    nsa.vars.direct_normal_transmittance_filter2.data; nsa.vars.direct_normal_transmittance_filter3.data; ...
    nsa.vars.direct_normal_transmittance_filter4.data; nsa.vars.direct_normal_transmittance_filter5.data],'-');
ylabel('Tr');
linkaxes(s,'x')
%%

Tr_1 = nsa.vars.direct_normal_narrowband_filter1.data .* ...
    (nsa.vars.sun_to_earth_distance.data.^2)./sscanf(nsa.atts.filter1_TOA_direct_normal.data,'%f');
Tr_2 = nsa.vars.direct_normal_narrowband_filter2.data .* ...
    (nsa.vars.sun_to_earth_distance.data.^2)./sscanf(nsa.atts.filter2_TOA_direct_normal.data,'%f');
Tr_3 = nsa.vars.direct_normal_narrowband_filter3.data .* ...
    (nsa.vars.sun_to_earth_distance.data.^2)./sscanf(nsa.atts.filter3_TOA_direct_normal.data,'%f');
Tr_4 = nsa.vars.direct_normal_narrowband_filter4.data .* ...
    (nsa.vars.sun_to_earth_distance.data.^2)./sscanf(nsa.atts.filter4_TOA_direct_normal.data,'%f');
Tr_5 = nsa.vars.direct_normal_narrowband_filter5.data .* ...
    (nsa.vars.sun_to_earth_distance.data.^2)./sscanf(nsa.atts.filter5_TOA_direct_normal.data,'%f');
%
figure; 
plot(serial2doy(nsa.time), [nsa.vars.direct_normal_transmittance_filter1.data;...
nsa.vars.direct_normal_transmittance_filter2.data;nsa.vars.direct_normal_transmittance_filter3.data;...
nsa.vars.direct_normal_transmittance_filter4.data;nsa.vars.direct_normal_transmittance_filter5.data],...
'x');
legend('1','2','3','4','5');

hold('on');
plot(serial2doy(nsa.time), [Tr_1; Tr_2; Tr_3; Tr_4; Tr_5],'k-');

% xlim([306.75,306.9])
